FROM node:22-alpine

WORKDIR /app

RUN corepack enable

COPY . .

RUN pnpm install --no-frozen-lockfile
RUN pnpm --filter @netflix-mini/types build
RUN pnpm --filter @netflix-mini/config build
RUN pnpm --filter api build

CMD ["pnpm", "--filter", "api", "start"]
